/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author User
 */
public class Nuevo extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo
     */
    public Nuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoTitulo = new javax.swing.JTextField();
        nuevoDirector = new javax.swing.JTextField();
        nuevoGenero = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        nuevoPrecio = new javax.swing.JTextField();
        nuevoInventario = new javax.swing.JTextField();
        nuevoAceptarButton = new javax.swing.JButton();
        fondoNuevo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nuevoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 240, 30));
        getContentPane().add(nuevoDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 240, 30));
        getContentPane().add(nuevoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 240, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, 30));
        getContentPane().add(nuevoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 240, 30));
        getContentPane().add(nuevoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 240, 30));

        nuevoAceptarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nuevoAceptarButton.setText("Confirmar");
        getContentPane().add(nuevoAceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 160, 40));

        fondoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Nuevo.png"))); // NOI18N
        getContentPane().add(fondoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoNuevo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton nuevoAceptarButton;
    private javax.swing.JTextField nuevoDirector;
    private javax.swing.JTextField nuevoGenero;
    private javax.swing.JTextField nuevoInventario;
    private javax.swing.JTextField nuevoPrecio;
    private javax.swing.JTextField nuevoTitulo;
    // End of variables declaration//GEN-END:variables
}
