/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author User
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGroup = new javax.swing.ButtonGroup();
        registerMail = new javax.swing.JTextField();
        registerUuario = new javax.swing.JTextField();
        registerNombre = new javax.swing.JTextField();
        registerApellido = new javax.swing.JTextField();
        registerEdad = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        registerContra = new javax.swing.JPasswordField();
        registerConfirmButton = new javax.swing.JButton();
        fondoRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(registerMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 240, 30));
        getContentPane().add(registerUuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 240, 30));
        getContentPane().add(registerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 240, 30));
        getContentPane().add(registerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 240, 30));
        getContentPane().add(registerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 240, 30));

        sexoGroup.add(jRadioButton1);
        jRadioButton1.setText("Mujer");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        sexoGroup.add(jRadioButton2);
        jRadioButton2.setText("Hombre");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));
        getContentPane().add(registerContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 240, 30));

        registerConfirmButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerConfirmButton.setText("CONFIRMAR");
        getContentPane().add(registerConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 180, 40));

        fondoRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Registro.png"))); // NOI18N
        getContentPane().add(fondoRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoRegister;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField registerApellido;
    private javax.swing.JButton registerConfirmButton;
    private javax.swing.JPasswordField registerContra;
    private javax.swing.JTextField registerEdad;
    private javax.swing.JTextField registerMail;
    private javax.swing.JTextField registerNombre;
    private javax.swing.JTextField registerUuario;
    private javax.swing.ButtonGroup sexoGroup;
    // End of variables declaration//GEN-END:variables
}
